name: Version/Compatibility Issue
description: Report issues related to Minecraft version compatibility or version switching
title: "[VERSION] "
labels: ["version", "compatibility"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Version Compatibility Issue
        
        Please provide details about version-related issues you're experiencing.

  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: Which Minecraft version are you using?
      options:
        - 1.21.4
        - 1.21.5
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of version issue are you experiencing?
      options:
        - Build failure after version switch
        - Dependency compatibility issue
        - Script/Workflow failure
        - Version detection problem
        - Other
    validations:
      required: true

  - type: textarea
    id: current-config
    attributes:
      label: Current Configuration
      description: Please paste your current gradle.properties content
      placeholder: |
        minecraft_version=1.21.5
        yarn_mappings=1.21.5+build.1
        fabric_version=0.128.2+1.21.5
        # ... etc
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: Error Message/Logs
      description: Paste any error messages or logs related to the issue
      placeholder: |
        [ERROR] Failed to resolve dependencies
        [ERROR] Version not found
        # ... etc

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How did you encounter this issue?
      placeholder: |
        1. Ran ./scripts/switch-version.sh 1.21.5
        2. Executed ./gradlew build
        3. Got error message...
      validations:
        required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: |
        The version should have switched successfully and the build should complete without errors.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: |
        - Operating System: Windows 10
        - Java Version: 21
        - Gradle Version: 8.5
        - Any custom modifications to the project

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked the [VERSION_SWITCHING.md](docs/VERSION_SWITCHING.md) documentation
          required: true
        - label: I have tried the troubleshooting steps
          required: true
        - label: I have checked for existing issues
          required: true
        - label: I have provided all requested information
          required: true
