name: Version Compatibility Check

on:
  schedule:
    # Check for new Minecraft versions daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  check-versions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Check current versions
      run: |
        echo "Current versions in gradle.properties:"
        echo "Minecraft: $(grep minecraft_version gradle.properties)"
        echo "Fabric: $(grep fabric_version gradle.properties)"
        echo "Meteor: $(grep meteor_version gradle.properties)"
        echo "Baritone: $(grep baritone_version gradle.properties)"

    - name: Test build with current version
      run: |
        echo "Testing build with current configuration..."
        ./gradlew build --no-daemon --stacktrace

    - name: Check for version updates
      run: |
        echo "Checking for available Minecraft versions..."
        # This could be extended to check external APIs for new versions
        echo "Current supported versions: 1.21.4, 1.21.5"
        echo "Current version: $(grep minecraft_version gradle.properties | cut -d'=' -f2)"

    - name: Create issue if build fails
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const currentVersion = process.env.CURRENT_VERSION || 'unknown';
          const issue = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `🚨 Build failure detected with Minecraft ${currentVersion}`,
            body: `## Build Failure Alert
            
            The automated build has failed with the current Minecraft version configuration.
            
            **Current Version:** ${currentVersion}
            **Failure Time:** ${new Date().toISOString()}
            
            Please check the [workflow run](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for more details.
            
            ### Possible Actions:
            - [ ] Check if dependencies need updating
            - [ ] Verify version compatibility
            - [ ] Update to a newer Minecraft version if available
            - [ ] Fix any breaking changes in the codebase
            
            ### 🤖 Automated by GitHub Actions
            This issue was created automatically by the Version Compatibility Check workflow.`,
            labels: ['build-failure', 'minecraft-version', 'automated']
          });
          
          console.log(`Created issue #${issue.data.number}`);
